id: I88470554
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-14T12:12:15+00:00'
last_modified: '2022-06-10T04:53:42.158665+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG09688
  title: ཇོ་བོ་རྗེ་དཔལ་ལྡན་ཨ་ཏི་ཤའི་རྣམ་ཐར་བཀའ་གདམས་ཕ་ཆོས་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4AAC:
      image_group_id: I00KG09718
      title: Volume 1 of jo bo rje dpal ldan a ti sha'i rnam thar bka' gdams pha chos
      total_pages: 910
      order: 1
      base_file: 4AAC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
